export const WalletConnectConstants = {
    WALLETCONNECTED: 'WALLETCONNECTED',
    WALLETDISCONNECTED: 'WALLETDISCONNECTED',
    CHAINCHANGED: 'CHAINCHANGED',
    ACCOUNTCHANGED: 'ACCOUNTCHANGED',
};